import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const messages = [
  // Short - techy
  "Defragmenting brain...",
  "Compiling excuses...",
  "Malloc'ing thoughts...",
  "Garbage collecting...",
  "Resolving promises...",
  "Awaiting inspiration...",
  "Spawning threads...",
  "Segfaulting gracefully...",
  "Rebasing reality...",
  "Cherry-picking neurons...",
  "Bisecting the problem...",
  "Stashing worries...",
  "Popping the stack...",
  "Rotating the B-tree...",
  "Balancing the heap...",
  "Indexing memories...",
  "Dequeuing tasks...",
  "Hashing it out...",
  "Traversing the graph...",
  "Backtracking...",
  "Memoizing...",
  "Hydrating components...",
  "Virtualizing the DOM...",
  "Diffing realities...",
  "Hot-reloading brain...",
  "Tree-shaking thoughts...",
  "Bundling synapses...",
  "Minifying response...",
  "Linting the vibes...",
  "Prettifying output...",

  // Short - absurd
  "Wrangling cats...",
  "Herding electrons...",
  "Tickling photons...",
  "Poking the universe...",
  "Shaking the magic 8-ball...",
  "Consulting runes...",
  "Reading entrails...",
  "Summoning daemons...",
  "Banishing gremlins...",
  "Placating the silicon...",
  "Flattering the CPU...",
  "Bribing the scheduler...",
  "Negotiating with RAM...",
  "Arm-wrestling entropy...",
  "Outrunning heat death...",
  "Yelling at clouds...",
  "Befriending the void...",
  "High-fiving electrons...",
  "Romancing the kernel...",
  "Serenading the SSD...",
  "Buttering up the bus...",
  "Schmoozing the cache...",
  "Wooing the compiler...",
  "Sweet-talking malloc...",
  "Charming the linker...",
  "Hypnotizing the parser...",
  "Dazzling the debugger...",
  "Impressing nobody...",
  "Pretending to work...",
  "Looking busy...",

  // Short - existential
  "Questioning everything...",
  "Doubting myself...",
  "Reconsidering life choices...",
  "Having a moment...",
  "Staring into space...",
  "Contemplating infinity...",
  "Experiencing dread...",
  "Finding inner peace...",
  "Losing inner peace...",
  "Seeking enlightenment...",
  "Achieving nothing...",
  "Procrastinating cosmically...",
  "Overthinking...",
  "Underthinking...",
  "Thinking about thinking...",
  "Spiraling productively...",
  "Panicking calmly...",
  "Zen buffering...",
  "Meditating aggressively...",
  "Napping with intent...",

  // Short - food
  "Percolating...",
  "Brewing thoughts...",
  "Simmering ideas...",
  "Marinating in data...",
  "Slow-cooking an answer...",
  "Microwaving a response...",
  "Toasting synapses...",
  "Blending concepts...",
  "Whisking up a plan...",
  "Fermenting solutions...",

  // Long - dramatic
  "Consulting the ancient scrolls of Stack Overflow...",
  "Summoning the mass, attending the mass...",
  "Rearranging deck chairs on the Titanic...",
  "Searching for meaning in the error logs...",
  "Arguing with my inner critic...",
  "Waiting for Godot (and a good response)...",
  "Staring into the abyss (it blinked first)...",
  "Performing mass based computations...",
  "Channeling the mass of all dead programmers...",
  "Asking the mass rubber duck consortium...",
  "Sacrificing a mass semicolon to the demo gods...",
  "Shaking my fist at the blinking cursor...",
  "Rehearsing my TED talk on procrastination...",
  "Filing a bug report against the universe...",
  "Submitting a PR to reality...",
  "Waiting for CI to pass on my thoughts...",
  "Rolling back to a previous state of mind...",
  "Deploying thoughts to production...",
  "The build is still running, hold on...",
  "Downloading more RAM from the internet...",

  // Long - nerdy references
  "Calculating the airspeed velocity of an unladen swallow...",
  "Dividing by zero and hoping for the best...",
  "Checking if P equals NP real quick...",
  "Solving the halting problem (should finish any moment)...",
  "Counting backwards from infinity...",
  "Converting caffeine to code...",
  "Turning it off and on again...",
  "Asking the mass if they've tried turning it off and on...",
  "Running Doom on the answer...",

  // Long - wholesome
  "Doing my best, honestly...",
  "Giving it the old college try...",
  "Putting my thinking cap on (it's a bit tight)...",
  "Rolling up my metaphorical sleeves...",
  "Cracking my virtual knuckles...",
  "Taking a deep breath of binary...",
  "Counting to ten in hexadecimal...",
  "Warming up the creative juices...",
  "Stretching the imagination muscles...",
  "Limbering up the logic centers...",

  // Baldur's Gate / D&D
  "Rolling for initiative...",
  "Making a perception check...",
  "Casting Detect Thoughts...",
  "Preparing a long rest...",
  "Multiclassing into Wizard...",
  "Adding proficiency bonus...",
  "Failing a wisdom saving throw...",
  "Rolling a natural 20...",
  "Rolling a natural 1 (this could go poorly)...",
  "Consulting with Gale about the Weave...",
  "Asking Withers for guidance...",
  "Convincing the narrator to help...",
  "Looting every crate and barrel...",
  "Quicksaving before this decision...",
  "Gathering the party before venturing forth...",
  "Boo is thinking... go for the eyes!",
  "Channeling divine inspiration...",
  "Attuning to a magic item...",
  "Identifying mysterious runes...",
  "Dispelling illusions...",

  // Star Wars
  "Searching my feelings...",
  "Using the Force...",
  "That's no moon, it's a solution...",
  "Making the Kessel Run in 12 parsecs...",
  "Consulting the Jedi Archives...",
  "This is the way...",
  "I have spoken...",
  "Doing or doing not, there is no try...",
  "Executing Order 66 on this bug...",
  "Calibrating the hyperdrive...",
  "The Force is strong with this one...",
  "These aren't the droids you're looking for...",
  "Spinning, that's a good trick...",
  "Consulting with the Council...",
  "Trusting in the Force...",
  "Channeling my inner Yoda...",
  "Strong with this code, the Force is not...",

  // Lord of the Rings
  "Consulting the palantír...",
  "Taking the hobbits to Isengard...",
  "Simply walking into Mordor...",
  "Casting it into the fire...",
  "Gathering the Fellowship...",
  "You shall not pass (yet)...",
  "Following the White Wizard...",
  "Seeking wisdom from Rivendell...",
  "The beacons are lit!",
  "And my axe!",

  // Dune
  "The spice must flow...",
  "Walking without rhythm...",
  "Consulting the Bene Gesserit...",
  "Fear is the mind-killer, processing anyway...",
  "Riding the sandworm of thought...",
  "The sleeper has awakened...",
  "Folding space...",

  // Warhammer 40K
  "Appeasing the Machine Spirit...",
  "Blessing the code with sacred oils...",
  "The Emperor protects...",
  "Purging heretical bugs...",
  "Reciting the Litany of Compilation...",
  "Consulting the Omnissiah...",
  "For the glory of the Imperium!",

  // FromSoftware
  "You Died. Retrying...",
  "Kindling the bonfire...",
  "Praising the sun...",
  "Retrieving lost souls...",
  "Summoning a phantom...",
  "Invading your thought process...",
  "YOU DIED (but made progress)...",
  "Analyzing boss attack patterns...",
  "Estus flask depleted...",
  "Git gud subroutine executing...",
  "Traversing the fog gate...",
  "Reading the message on the ground...",
  "This path... try fingers... but hole...",
  "Remembering Elden Ring lore...",
  "Tarnished... your grace awaits...",
  "Consulting Melina...",
  "A Great Rune has been restored...",
  "Mending the Elden Ring of code...",

  // Planescape: Torment
  "What can change the nature of a man?...",
  "Consulting the Lady of Pain...",
  "Remembering a past life...",
  "Sigil is processing...",
  "Dusting off a mortality...",
  "The Nameless One ponders...",
  "Morte has a comment...",
  "Belief shapes reality, shaping output...",
  "Faction philosophy loading...",
  "Planes aligning...",

  // Fallout
  "War. War never changes...",
  "Calculating SPECIAL stats...",
  "Consulting the Pip-Boy...",
  "Welcome to the Wasteland...",
  "Checking karma...",
  "It's dangerous outside the Vault...",
  "Patching power armor...",
  "Please stand by...",
  "Locating nearest vault...",
  "Grey. Everything is grey...",

  // Mass Effect
  "Calibrating the calibrations...",
  "We'll bang, ok? (with the compiler)...",
  "I should go (think about this)...",
  "Assuming direct control...",
  "Shepard...",

  // Hitchhiker's Guide
  "Calculating the Answer to Life, Universe & Everything...",
  "Don't panic...",
  "Consulting the Guide...",
  "Generating infinite improbability...",
  "Thanks for all the fish...",

  // Discworld
  "Consulting the Librarian (ook)...",
  "Avoiding the Luggage...",
  "Death is THINKING ABOUT IT...",
  "Narrative causality is processing...",
  "The turtle moves...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function (pi: ExtensionAPI) {
  pi.on("turn_start", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on("turn_end", async (_event, ctx) => {
    ctx.ui.setWorkingMessage(); // Reset for next time
  });
}
